import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "index.ts",
    "demo-core/index.ts",
    "demo-core/storage.ts",
    "demo-core/knowledge.ts",
    "demo-core/demo-core-config.ts",
    "providers/openai-adapter.ts",
    "providers/anthropic-adapter.ts",
    "providers/gemini-adapter.ts",
    "trial/gateway.ts",
    "trial/hash.ts",
    "trial/http.ts",
    "trial/admin.ts",
    "trial/redis.ts",
    "trial/rate-limiter.ts",
    "trial/concurrency-lock.ts",
    "trial/server-adapters.ts",
    "trial/spend-reservation.ts",
    "trial/trial-validator.ts",
    "trial/usage-ledger.ts",
    "config/provider.config.ts",
    "config/pricing.config.ts",
    "config/trial-policy.config.ts",
    "types/access-mode.ts",
    "types/provider.ts",
    "types/trial.ts",
    "types/errors.ts",
    "types/usage.ts",
  ],
  format: ["esm"],
  dts: true,
  splitting: true,
  clean: true,
  sourcemap: true,
  outDir: "dist",
  external: ["@upstash/redis", "pdfjs-dist"],
});
